In [ ]:
import tensorflow as tf

print("GPU disponible:", tf.config.list_physical_devices('GPU'))

# Instalar librerías adicionales si es necesario
!pip install seaborn plotly

# Importaciones estándar
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

# Configuración de visualización
plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12

print("Entorno configurado correctamente en Google Colab")


GPU disponible: []
Entorno configurado correctamente en Google Colab


In [ ]:
# Opción 1: Datasets integrados
import seaborn as sns
titanic = sns.load_dataset('titanic')
iris = sns.load_dataset('iris')


In [ ]:
#Crea un array del 1 al 10
import numpy as np
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Matriz identidad de tamaño 5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Convertir algunas columnas numéricas a arrays NumPy:
age = titanic['age'].to_numpy()
fare = titanic['fare'].to_numpy()
pclass = titanic['pclass'].to_numpy()
survived = titanic['survived'].to_numpy()
print(age)
print(fare)
print(pclass)
print(survived)

[22.   38.   26.   35.   35.     nan 54.    2.   27.   14.    4.   58.
 20.   39.   14.   55.    2.     nan 31.     nan 35.   34.   15.   28.
  8.   38.     nan 19.     nan   nan 40.     nan   nan 66.   28.   42.
   nan 21.   18.   14.   40.   27.     nan  3.   19.     nan   nan   nan
   nan 18.    7.   21.   49.   29.   65.     nan 21.   28.5   5.   11.
 22.   38.   45.    4.     nan   nan 29.   19.   17.   26.   32.   16.
 21.   26.   32.   25.     nan   nan  0.83 30.   22.   29.     nan 28.
 17.   33.   16.     nan 23.   24.   29.   20.   46.   26.   59.     nan
 71.   23.   34.   34.   28.     nan 21.   33.   37.   28.   21.     nan
 38.     nan 47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.
 21.     nan 32.5  32.5  54.   12.     nan 24.     nan 45.   33.   20.
 47.   29.   25.   23.   19.   37.   16.   24.     nan 22.   24.   19.
 18.   19.   27.    9.   36.5  42.   51.   22.   55.5  40.5    nan 51.
 16.   30.     nan   nan 44.   40.   26.   17.    1.    9.     nan 45.


In [ ]:
#Reemplazar edades faltantes (NaN) por la media
age_filled = age.copy()
age_filled[np.isnan(age_filled)] = np.nanmean(age_filled)
print(age_filled, round (2))

[22.         38.         26.         35.         35.         29.69911765
 54.          2.         27.         14.          4.         58.
 20.         39.         14.         55.          2.         29.69911765
 31.         29.69911765 35.         34.         15.         28.
  8.         38.         29.69911765 19.         29.69911765 29.69911765
 40.         29.69911765 29.69911765 66.         28.         42.
 29.69911765 21.         18.         14.         40.         27.
 29.69911765  3.         19.         29.69911765 29.69911765 29.69911765
 29.69911765 18.          7.         21.         49.         29.
 65.         29.69911765 21.         28.5         5.         11.
 22.         38.         45.          4.         29.69911765 29.69911765
 29.         19.         17.         26.         32.         16.
 21.         26.         32.         25.         29.69911765 29.69911765
  0.83       30.         22.         29.         29.69911765 28.
 17.         33.         16.         29.69

In [ ]:
#Crear un array 2D (matriz) con [edad, clase, tarifa]
matrix = np.column_stack((age, pclass, fare))
print(matrix, round (2))

[[22.      3.      7.25  ]
 [38.      1.     71.2833]
 [26.      3.      7.925 ]
 ...
 [    nan  3.     23.45  ]
 [26.      1.     30.    ]
 [32.      3.      7.75  ]] 2


In [ ]:
#Calcular el máximo, mínimo y promedio del precio del billete
fare_min = np.nanmin(fare)
fare_max = np.nanmax(fare)
fare_mean = np.nanmean(fare)
print("valor min billete", "=", f"{fare_min:.2f}")
print("valor max billete", "=", f"{fare_max:.2f}")
print("valor prom billete", "=", f"{fare_mean:.2f}")

valor min billete = 0.00
valor max billete = 512.33
valor prom billete = 32.20


In [ ]:
#Análisis Panda I - Información General
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
#Análisis Panda I - Resumen estadístico
titanic.describe(include="all"). round(2)

survived  pclass   sex     age   sibsp   parch    fare embarked  \
count     891.00  891.00   891  714.00  891.00  891.00  891.00      889   
unique       NaN     NaN     2     NaN     NaN     NaN     NaN        3   
top          NaN     NaN  male     NaN     NaN     NaN     NaN        S   
freq         NaN     NaN   577     NaN     NaN     NaN     NaN      644   
mean        0.38    2.31   NaN   29.70    0.52    0.38   32.20      NaN   
std         0.49    0.84   NaN   14.53    1.10    0.81   49.69      NaN   
min         0.00    1.00   NaN    0.42    0.00    0.00    0.00      NaN   
25%         0.00    2.00   NaN   20.12    0.00    0.00    7.91      NaN   
50%         0.00    3.00   NaN   28.00    0.00    0.00   14.45      NaN   
75%         1.00    3.00   NaN   38.00    1.00    0.00   31.00      NaN   
max         1.00    3.00   NaN   80.00    8.00    6.00  512.33      NaN   

        class  who adult_male deck  embark_town alive alone  
count     891  891        891  203          889   891   891  
unique      3    3          2    7            3     2     2  
top     Third  man       True    C  Southampton    no  True  
freq      491  537        537   59          644   549   537  
mean      NaN  NaN        NaN  NaN          NaN   NaN   NaN  
std       NaN  NaN        NaN  NaN          NaN   NaN   NaN  
min       NaN  NaN        NaN  NaN          NaN   NaN   NaN  
25%       NaN  NaN        NaN  NaN          NaN   NaN   NaN  
50%       NaN  NaN        NaN  NaN          NaN   NaN   NaN  
75%       NaN  NaN        NaN  NaN          NaN   NaN   NaN  
max       NaN  NaN        NaN  NaN          NaN   NaN   NaN